services:
  - type: web
    name: mentor-mentee-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
    autoDeploy: true
    healthCheckPath: /
